In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv("homeprices.csv")

In [3]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model=linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

180616.43835616432

In [11]:
model.predict([[5000]])

C:\Users\Emboss\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [12]:
#using pickle
import pickle

In [13]:
with open('model_pickle','wb')as f:
    pickle.dump(model,f)

In [14]:
with open ('model_pickle','rb')as f:
    mp=pickle.load(f)

In [15]:
mp.predict([[5000]])

C:\Users\Emboss\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [17]:
#using jobli
import joblib

In [18]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [19]:
mj=joblib.load('model_joblib')

In [20]:
mj.predict([[5000]])

C:\Users\Emboss\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [21]:
mj.coef_

array([135.78767123])

In [22]:
mj.intercept_

180616.43835616432